@extends('errors.layout')
@section('code', '419')
@section('title', 'Session expired')
@section('icon', 'clock-countdown')
@section('message', "Your session expired for security reasons. Please go back, refresh the page and try again.")
