@extends('errors.layout')
@section('code', '500')
@section('title', 'Something went wrong')
@section('icon', 'warning-octagon')
@section('message', "An unexpected error occurred. Please try again in a moment.")
